services:
  postgres:
    container_name: postgres_todo_app_tg_bot
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5433:5432'
    volumes:
      - postgres_todo_app_tg_bot_data:/var/lib/postgresql/data
    networks:
      - nestjs-todo-app-tg-bot

volumes:
  postgres_todo_app_tg_bot_data:

networks:
  nestjs-todo-app-tg-bot:
